# Generated by Django 5.1.1 on 2024-09-25 05:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazar_app', '0005_contact_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
