# Generated by Django 5.1.1 on 2024-09-25 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bazar_app', '0007_alter_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='published_at',
        ),
    ]
