# Generated by Django 5.1.1 on 2024-09-25 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bazar_app', '0012_alter_product_published_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='content',
        ),
    ]
